version: "3.8"
services:
    db:
      ports:
        - "3306:3306"
    backend:
      ports:
        - "3000:3000"
        - "9229:9229"
      volumes:
        - ./backend/.:/app
        - ./backend/node_modules:/app/node_modules
      command: npm run start:debug
    frontend:
      ports:
        - "4000:4000"
      volumes:
        - ./frontend-TS/.:/app/
        - ./frontend-TS/node_modules:/app/node_modules
